### ISSUE TITLE
POC requirements

### ISSUE THREAD

**Issue by Danwhy** [cul-2016/study-planner#1]
### Initial requirements for Study Planner proof of concept/MVP

* [ ] Student can add assessments (date, name, type, importance/amount of work) #2 
* [ ] Student can add target amount of work for the week #3 
* [ ]  Calculation of how much time to spend on each assessment (@stianr to provide algorithm) #4 
* [ ] Displaying Assessments/targets/completion #5 
* [ ] Students can log time against assessments #6 
* [ ] Timer to allow users to time their work #7 
* [ ] Timer automatically logs time to assessment #8 
* [ ] New: Aspects of gamification – creating alerts, motivating comments etc. – to be confirmed. #9

**Comment by Danwhy** [comment]
@stianr I've added all the issues, so feel free to take a look and amend them as you wish
